apiVersion: v2.edp.epam.com/v1alpha1
kind: Gerrit
metadata:
  name: example-gerrit
spec:
  type: "Gerrit"
  sshPort: ""
  version: '2.16.10'
  keycloakSpec:
    enabled: false
    url: ""
  volumes:
    - name: "data"
      storage_class: "gp2"
      capacity: "1Gi"
  users:
    - username: test@edp.com
      groups:
        - Administrators